### ISSUE TITLE
CUDA Samples: Something important to note (regarding CUDA samples, as well as netcdf/netcdf-cxx lib integration)

### ISSUE THREAD

**Issue by briidee3** [JasonApke/OCTANE#2]
As of CUDA 11, samples aren't automatically installed, and need to be installed manually.

The way I did it was by simply getting the samples from the [GitHub repo from NVIDIA](https://github.com/NVIDIA/cuda-samples/tree/master/) and manually putting the files into the install folder for cuda (e.g. /usr/local/cuda-11.8), however there may be a better way of doing this.

I would recommend adding the samples to this repo, so as to prevent issues for others who may want to use OCTANE in the future.

On another note, I would also like to mention that one way of implementing netcdf/netcdf-cxx (on Ubuntu 20.04 at least, as I've been doing this all in Google Colab) is to simply use apt to install libnetcdf-c++4-dev and netcdf-bin and netcdf-doc (not sure if that last one is necessary, but it doesn't seem to hurt), and then for NCLOC and NCCPPLOC in the Makefile in /src, set it to /usr . This worked just fine for me in my case, but there may also be some nuances due to the fact that Colab runs in a docker container (TL;DR: YMMV). 

I only felt the need to mention the netcdf/netcdf-cxx situation because it took me a couple hours to figure out how to get it to work in Colab lol, and I was trying things like compiling legacy versions of netcdf-cxx from source and jumping through a bunch of unnecessary hoops before realizing the answer was there all along (and much simpler, thankfully!)

**Comment by JasonApke** [comment]
Yes the samples were recently separated right after I uploaded this version.  Can't include them directly in this repository due to licensing restrictions, however, all they are currently used for is for is the cuda error checking function, which is a dependency I have removed with later additions to the code.  Will upload that modification soon.

**Comment by JasonApke** [comment]
The cuda samples dependency has been removed with the latest additions to the makefile and variational_optical_flow.cu .  Thanks for the suggestions!
